import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-indigo/theme.css"; // Choose your preferred theme
import "primereact/resources/primereact.min.css"; // PrimeReact core styles
import "primeicons/primeicons.css"; // PrimeIcons
import "primeflex/primeflex.css";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "600", "700"], // Customize the weights you need
});

export const metadata: Metadata = {
  title: "Wedding Invitation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-white m-0 p-0 text-black-alpha-60`}
      >
        <PrimeReactProvider>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
